In [16]:
import numpy as np
import time

# Step 1: Generate two random 100x100 arrays
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Step 2: Start the timer
start_time = time.time()
print(f"Operation Start time :{start_time} \n")

# Step 3: Matrix multiplication
C = np.dot(A, B)
print("Matrix multiplication completed.\n")
print(C,"\n")


# Step 4: Calculate determinant
det_C = np.linalg.det(C)
print(f"Determinant of the result: {det_C} \n")


# Step 5: Try to calculate inverse if determinant is not zero
if np.isclose(det_C, 0):
    inverse_C = None
    invertible = False
else:
    inverse_C = np.linalg.inv(C)
    invertible = True

# Step 6: End the timer
end_time = time.time()
print(f"Operation end time :{end_time} \n")
elapsed_time = end_time - start_time

# Step 7: Print results
print("Matrix is invertible." if invertible else "Matrix is not invertible.")
if invertible:
    print("Inverse matrix calculated successfully.")
    print(inverse_C,"\n")
print(f"Time taken: {elapsed_time:.4f} seconds")

Operation Start time :1752301495.80621 

Matrix multiplication completed.

[[23.10880013 21.15736831 21.42143211 ... 18.93790773 23.07773765
  24.97216534]
 [24.60703391 23.08647365 23.29144982 ... 22.0236202  23.97871586
  25.85996957]
 [24.53907556 22.32766266 22.91428153 ... 20.40317068 24.01770634
  27.48175484]
 ...
 [25.20608484 24.98598621 24.43569469 ... 23.05524906 24.91950769
  27.09684551]
 [24.69686567 24.48760929 23.37299701 ... 21.21762697 24.96667686
  27.3569613 ]
 [26.47198115 25.32273197 25.23869973 ... 23.01835895 25.32922075
  30.18504778]] 

Determinant of the result: -1.4997739509369783e+51 

Operation end time :1752301495.8543262 

Matrix is invertible.
Inverse matrix calculated successfully.
[[  3.00130534  -4.75414478 -22.04907933 ...  -2.8056522   -6.1083369
  -20.73194027]
 [  0.23025603  -2.36135664 -12.3710645  ...  -0.92733719  -2.92715506
  -13.85834691]
 [  1.04125886  -1.64565734  -6.01496236 ...  -0.54946395  -1.44762693
   -5.97206896]
 ...
 [ -0.2560

In [15]:
# Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

import numpy as np
l3=np.random.randint(1,100,20)
print("Original Array :-")
print(l3)
print("Sorted Array :-")
print(np.sort(l3))
print("5 largest elements")
print(np.sort(l3)[-5:][::-1])

Original Array :-
[19 74 59 60 94 47  2 18 21 24 47 59 38 88 93 83 62 48 52 32]
Sorted Array :-
[ 2 18 19 21 24 32 38 47 47 48 52 59 59 60 62 74 83 88 93 94]
5 largest elements
[94 93 88 83 74]


In [14]:
# Create an identity matrix of size 4x4.
import numpy as np
print(np.eye(4,dtype="int"))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
# Create an array of 10 equally spaced values between 0 and 1.
import numpy as np
l1=np.linspace(0,1,10)
print("Array of 10 equally spaced values between 0 and 1 \n")
print(l1)

Array of 10 equally spaced values between 0 and 1 

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
import numpy as np

l2=np.random.randint(10,50,15)
print(l2)
print("Numbers Greater than 25 :")
print(l2[l2>25])
print("Replacing all elements less than 30 with 0 :")
l2[l2<30]=0
print(l2)
print("number of nonZero elements divisible by 5")
print(np.count_nonzero(l2[l2%5==0]))
print("number of  elements divisible by 5")
print(np.count_nonzero(l2%5==0))

In [12]:
import numpy as np

l1=np.random.randint(1,12,12)
print(l1)
print("2D Array of Size 4X3")
print(l1.reshape(4,3))
print("3D Array of Size 2X2X3  ")
print(l1.reshape(2,2,3))
print("Transpose of 2D Array")
print(np.transpose(l1.reshape(4,3)))
print("Transpose of 2D Array and its shape")
print(np.transpose(l1.reshape(4,3)).shape)

[ 1  5  4  2  9  1  5  4  1  6 11 10]
2D Array of Size 4X3
[[ 1  5  4]
 [ 2  9  1]
 [ 5  4  1]
 [ 6 11 10]]
3D Array of Size 2X2X3  
[[[ 1  5  4]
  [ 2  9  1]]

 [[ 5  4  1]
  [ 6 11 10]]]
Transpose of 2D Array
[[ 1  2  5  6]
 [ 5  9  4 11]
 [ 4  1  1 10]]
Transpose of 2D Array and its shape
(3, 4)


In [11]:
# Identify the maximum and minimum values in array B and their indices
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(B)
print("Maximum :",np.max(B))
print("Minimum :",np.min(B))
print("Maximum idx :",np.argmax(B))
print("Minimum idx :",np.argmin(B))

[ 9 15 10  8 18]
Maximum : 18
Minimum : 8
Maximum idx : 4
Minimum idx : 3


In [ ]:
# Find the mean, median, standard deviation, and variance o--> array A.
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print("Mean :",np.mean(A))
print("Median :",np.median(A))
print("Standard deviation :",np.std(A))
print("Varience :",np.var(A))

In [10]:
# Compute the dot product of the arrays.
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
dot_product = np.dot(A, B)
# Or alternatively:
# dot_product = A @ B
print(dot_product)

[ 8  1  2 11  2]
[11 18  6  4 19]
200


In [9]:
# Add, subtract, multiply, and divide the two arrays element-wise.
import numpy as np
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
add=A+B
sub=A-B
mul=A*B
div=A/B
print("Addition :",add)
print("Subtraction :",sub)
print("Multiplication :",mul)
print("Division:",div)

[ 6  4 14  6 13]
[ 5  7 17 10 14]
Addition : [11 11 31 16 27]
Subtraction : [ 1 -3 -3 -4 -1]
Multiplication : [ 30  28 238  60 182]
Division: [1.2        0.57142857 0.82352941 0.6        0.92857143]


In [8]:
import numpy as np
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
l1=np.array(data)
print(l1[0:3])
print(l1[::2])
print(l1[::-1])

[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [7]:
import numpy as np
l3=np.random.rand(3,5,3)
print(l3.shape)
print(l3.size)
print(type(l3))
l3

(3, 5, 3)
45
<class 'numpy.ndarray'>


array([[[0.27625968, 0.39782854, 0.99898161],
        [0.41250693, 0.80519191, 0.60798709],
        [0.7326433 , 0.70312408, 0.27568408],
        [0.84194764, 0.51371022, 0.32715145],
        [0.23513682, 0.09167083, 0.3047352 ]],

       [[0.87953413, 0.24387161, 0.36107583],
        [0.78133098, 0.22486828, 0.92258738],
        [0.37127311, 0.299724  , 0.03068377],
        [0.01857258, 0.5703783 , 0.61486505],
        [0.55383191, 0.00834434, 0.18233749]],

       [[0.63966072, 0.55021727, 0.77250862],
        [0.02333941, 0.40026031, 0.15773123],
        [0.54778345, 0.73529097, 0.16299174],
        [0.44429068, 0.69021054, 0.71906959],
        [0.5636323 , 0.23515827, 0.98219908]]])

In [4]:
pip install numpy

     ---------------------------------------- 13.0/13.0 MB 3.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np
l2=np.random.randint(1,10,9).reshape(3,3)
print(l2.shape)
print(l2.size)
print(type(l2))
l2

(3, 3)
9
<class 'numpy.ndarray'>


array([[9, 6, 1],
       [3, 2, 1],
       [2, 3, 9]], dtype=int32)

In [5]:
import numpy as np
l1=np.random.randint(1,11,10)
print(l1.shape)
print(l1.size)
print(type(l1))
l1

(10,)
10
<class 'numpy.ndarray'>


array([1, 5, 1, 6, 3, 7, 6, 4, 5, 3], dtype=int32)